@PROJETO22.CSV_CUSTOMER_IMPORT.CHALLENGE.API_HostAddress = http://localhost:5164

POST {{PROJETO22.CSV_CUSTOMER_IMPORT.CHALLENGE.API_HostAddress}}/clientes/importar
Content-Type: multipart/form-data

###
